import Link from 'next/link'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <style>
          {`
            /* Barra superior */
            nav {
              display: flex;
              justify-content: space-between;
              align-items: center;
              background-color:rgb(255, 255, 255);
              color:rgb(0, 0, 0);
              padding: 35px 20px;
            }

            nav h1 {
              margin: 0;
            }

            nav ul {
              list-style: none;
              display: flex;
              margin: 0;
            }

            nav ul li {
              margin-left: 20px;
            }

            nav ul li a {
              color:rgb(0, 0, 0);
              text-decoration: none;
              font-size: 20px;
            }

            nav ul li a:hover {
              color:#634AFF;
            }
          `}
        </style>
      </head>
      <body>
        <nav>
          <h1>Rescata un Amigo</h1>
          <ul>
            <li><Link href="/">Inicio</Link></li>
            <li><Link href="/accesos/login">Iniciar sesión</Link></li>
            <li><Link href="/accesos/register">Registrarse</Link></li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  )
}
