import Link from 'next/link'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <style>
          {`
            /* Barra superior */
            nav {
              display: flex;
              justify-content: space-between;
              align-items: center;
              background-color: #333;
              color: white;
              padding: 10px 20px;
            }

            nav h1 {
              margin: 0;
            }

            nav ul {
              list-style: none;
              display: flex;
              margin: 0;
            }

            nav ul li {
              margin-left: 20px;
            }

            nav ul li a {
              color: white;
              text-decoration: none;
              font-size: 16px;
            }

            nav ul li a:hover {
              text-decoration: underline;
            }
          `}
        </style>
      </head>
      <body>
        <nav>
          <h1>My Pet</h1>
          <ul>
            <li><Link href="/">Home</Link></li>
            <li><Link href="/accesos/login">Login</Link></li>
            <li><Link href="/accesos/register">Register</Link></li>
          </ul>
        </nav>
        
        {children}
      </body>
    </html>
  )
}
